export const Answer = [
  {
    "ID": 1,
    "AnswerName": "Bespoke",
    "Description": "Application",
    "Sequence": 1,
    "QuestionID": 1,
    "IconURL": "",
    "NextQuestionID": 2,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 2,
    "AnswerName": "SAAS",
    "Description": "SAAS",
    "Sequence": 2,
    "QuestionID": 1,
    "IconURL": "",
    "NextQuestionID": "",
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 3,
    "AnswerName": "Windows",
    "Description": "Microsoft Corporation",
    "Sequence": 1,
    "QuestionID": 2,
    "IconURL": "",
    "NextQuestionID": 3,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 4,
    "AnswerName": "Mac",
    "Description": "Apple Inc",
    "Sequence": 2,
    "QuestionID": 2,
    "IconURL": "",
    "NextQuestionID": 3,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 5,
    "AnswerName": "OnPrem",
    "Description": "On-premises",
    "Sequence": 1,
    "QuestionID": 3,
    "IconURL": "",
    "NextQuestionID": 5,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 6,
    "AnswerName": "Cloud",
    "Description": "Cloud",
    "Sequence": 2,
    "QuestionID": 3,
    "IconURL": "",
    "NextQuestionID": 4,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 7,
    "AnswerName": "Azure",
    "Description": "Microsoft Azure Cloud",
    "Sequence": 1,
    "QuestionID": 4,
    "IconURL": "",
    "NextQuestionID": 5,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 8,
    "AnswerName": "AWS",
    "Description": "Amazon Cloud",
    "Sequence": 2,
    "QuestionID": 4,
    "IconURL": "",
    "NextQuestionID": 5,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 9,
    "AnswerName": "Google",
    "Description": "Google Cloud",
    "Sequence": 3,
    "QuestionID": 4,
    "IconURL": "",
    "NextQuestionID": 5,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 10,
    "AnswerName": "Internal Users",
    "Description": "Internal users are people within a business organization",
    "Sequence": 1,
    "QuestionID": 5,
    "IconURL": "",
    "NextQuestionID": 6,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 11,
    "AnswerName": "External Users",
    "Description": "External users are entities or individuals who do not participate in running or managing the business",
    "Sequence": 2,
    "QuestionID": 5,
    "IconURL": "",
    "NextQuestionID": 7,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 12,
    "AnswerName": "Internal and External Users",
    "Description": "Both type of Users",
    "Sequence": 3,
    "QuestionID": 5,
    "IconURL": "",
    "NextQuestionID": "6,7",
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 13,
    "AnswerName": "Staff",
    "Description": "Staff",
    "Sequence": 1,
    "QuestionID": 6,
    "IconURL": "",
    "NextQuestionID": 8,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 14,
    "AnswerName": "Administrators",
    "Description": "Administrators",
    "Sequence": 2,
    "QuestionID": 6,
    "IconURL": "",
    "NextQuestionID": 8,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 15,
    "AnswerName": "Customers",
    "Description": "Customers",
    "Sequence": 1,
    "QuestionID": 7,
    "IconURL": "",
    "NextQuestionID": 8,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 16,
    "AnswerName": "Moderators",
    "Description": "Moderators",
    "Sequence": 2,
    "QuestionID": 7,
    "IconURL": "",
    "NextQuestionID": 8,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 17,
    "AnswerName": "Framework",
    "Description": "Angular",
    "Sequence": 1,
    "QuestionID": 8,
    "IconURL": "",
    "NextQuestionID": 9,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 18,
    "AnswerName": "Framework",
    "Description": "Ionic",
    "Sequence": 2,
    "QuestionID": 8,
    "IconURL": "",
    "NextQuestionID": 9,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 19,
    "AnswerName": "Framework",
    "Description": "ReactJs",
    "Sequence": 3,
    "QuestionID": 8,
    "IconURL": "",
    "NextQuestionID": 9,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 20,
    "AnswerName": "Framework",
    "Description": "VueJs",
    "Sequence": 4,
    "QuestionID": 8,
    "IconURL": "",
    "NextQuestionID": 9,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 21,
    "AnswerName": "Framework",
    "Description": "Polymer",
    "Sequence": 5,
    "QuestionID": 8,
    "IconURL": "",
    "NextQuestionID": 9,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 22,
    "AnswerName": "Framework",
    "Description": "Aurelia",
    "Sequence": 6,
    "QuestionID": 8,
    "IconURL": "",
    "NextQuestionID": 9,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 23,
    "AnswerName": "UI Framework",
    "Description": "Bootstrap",
    "Sequence": 1,
    "QuestionID": 9,
    "IconURL": "",
    "NextQuestionID": 10,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 24,
    "AnswerName": "UI Framework",
    "Description": "Angular Material UI",
    "Sequence": 2,
    "QuestionID": 9,
    "IconURL": "",
    "NextQuestionID": 10,
    "DepQuestionID": 8,
    "DepAnswerID": 17
  },
  {
    "ID": 25,
    "AnswerName": "UI Framework",
    "Description": "Material-UI",
    "Sequence": 3,
    "QuestionID": 9,
    "IconURL": "",
    "NextQuestionID": 10,
    "DepQuestionID": 8,
    "DepAnswerID": 19
  },
  {
    "ID": 26,
    "AnswerName": "UI Framework",
    "Description": "Ionic UI",
    "Sequence": 4,
    "QuestionID": 9,
    "IconURL": "",
    "NextQuestionID": 10,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 27,
    "AnswerName": "UI Framework",
    "Description": "Aurelia UI Framework",
    "Sequence": 5,
    "QuestionID": 9,
    "IconURL": "",
    "NextQuestionID": 10,
    "DepQuestionID": 8,
    "DepAnswerID": 22
  },
  {
    "ID": 28,
    "AnswerName": "Access",
    "Description": "Local Logins",
    "Sequence": 1,
    "QuestionID": 10,
    "IconURL": "",
    "NextQuestionID": 12,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 29,
    "AnswerName": "Access",
    "Description": "Single Signon",
    "Sequence": 2,
    "QuestionID": 10,
    "IconURL": "",
    "NextQuestionID": 11,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 30,
    "AnswerName": "SSO",
    "Description": "Azure AD",
    "Sequence": 1,
    "QuestionID": 11,
    "IconURL": "",
    "NextQuestionID": 12,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 31,
    "AnswerName": "SSO",
    "Description": "Google Login",
    "Sequence": 2,
    "QuestionID": 11,
    "IconURL": "",
    "NextQuestionID": 12,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 32,
    "AnswerName": "SSO",
    "Description": "Facebook Login",
    "Sequence": 3,
    "QuestionID": 11,
    "IconURL": "",
    "NextQuestionID": 12,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 33,
    "AnswerName": "SSO",
    "Description": "Amazon Login",
    "Sequence": 4,
    "QuestionID": 11,
    "IconURL": "",
    "NextQuestionID": 12,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 34,
    "AnswerName": "Data Store",
    "Description": "Relational Database",
    "Sequence": 1,
    "QuestionID": 12,
    "IconURL": "",
    "NextQuestionID": 13,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 35,
    "AnswerName": "Data Store",
    "Description": "No SQL Database",
    "Sequence": 2,
    "QuestionID": 12,
    "IconURL": "",
    "NextQuestionID": 14,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 36,
    "AnswerName": "Relational Database",
    "Description": "SQL Server",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 3,
    "DepAnswerID": 5
  },
  {
    "ID": 37,
    "AnswerName": "Relational Database",
    "Description": "Oracle",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 3,
    "DepAnswerID": 5
  },
  {
    "ID": 38,
    "AnswerName": "Relational Database",
    "Description": "Azure SQL Database",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 7
  },
  {
    "ID": 39,
    "AnswerName": "Relational Database",
    "Description": "Azure SQL Managed Instance",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 7
  },
  {
    "ID": 40,
    "AnswerName": "Relational Database",
    "Description": "Amazon Redshift",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 8
  },
  {
    "ID": 41,
    "AnswerName": "Relational Database",
    "Description": "Amazon RDS",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 8
  },
  {
    "ID": 42,
    "AnswerName": "Relational Database",
    "Description": "Amazon Aurora",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 8
  },
  {
    "ID": 43,
    "AnswerName": "Relational Database",
    "Description": "Cloud SQL",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 9
  },
  {
    "ID": 44,
    "AnswerName": "Relational Database",
    "Description": "Cloud Spanner",
    "Sequence": "",
    "QuestionID": 13,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 9
  },
  {
    "ID": 45,
    "AnswerName": "NoSQL Database",
    "Description": "MongoDB",
    "Sequence": "",
    "QuestionID": 14,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 3,
    "DepAnswerID": 5
  },
  {
    "ID": 46,
    "AnswerName": "NoSQL Database",
    "Description": "Couchbase",
    "Sequence": "",
    "QuestionID": 14,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 3,
    "DepAnswerID": 5
  },
  {
    "ID": 47,
    "AnswerName": "NoSQL Database",
    "Description": "Azure Cosmos DB",
    "Sequence": "",
    "QuestionID": 14,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 7
  },
  {
    "ID": 48,
    "AnswerName": "NoSQL Database",
    "Description": "Amazon DynamoDB",
    "Sequence": "",
    "QuestionID": 14,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 8
  },
  {
    "ID": 49,
    "AnswerName": "NoSQL Database",
    "Description": "Cloud Bigtable",
    "Sequence": "",
    "QuestionID": 14,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 9
  },
  {
    "ID": 50,
    "AnswerName": "NoSQL Database",
    "Description": "Cloud Firestore",
    "Sequence": "",
    "QuestionID": 14,
    "IconURL": "",
    "NextQuestionID": 15,
    "DepQuestionID": 4,
    "DepAnswerID": 9
  },
  {
    "ID": 51,
    "AnswerName": "Integration",
    "Description": "Build API's",
    "Sequence": "",
    "QuestionID": 15,
    "IconURL": "",
    "NextQuestionID": "",
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 52,
    "AnswerName": "Integration",
    "Description": "Integrate with API Gateway",
    "Sequence": "",
    "QuestionID": 15,
    "IconURL": "",
    "NextQuestionID": 16,
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 53,
    "AnswerName": "Integration Gateway",
    "Description": "MuleSoft",
    "Sequence": "",
    "QuestionID": 16,
    "IconURL": "",
    "NextQuestionID": "",
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 54,
    "AnswerName": "Integration Gateway",
    "Description": "Apigee",
    "Sequence": "",
    "QuestionID": 16,
    "IconURL": "",
    "NextQuestionID": "",
    "DepQuestionID": "",
    "DepAnswerID": ""
  },
  {
    "ID": 55,
    "AnswerName": "Integration Gateway",
    "Description": "Dell Boomi",
    "Sequence": "",
    "QuestionID": 16,
    "IconURL": "",
    "NextQuestionID": "",
    "DepQuestionID": "",
    "DepAnswerID": ""
  }
]
